language: ruby
rvm:
  - ruby-head
  - ree
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.1
  - jruby-18mode
  - jruby-19mode
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
addons:
  code_climate:
    repo_token: 4043bdd174c4a44e3f6907accb45c96aade61c3a096db499b72d47f77fc1fead
